/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author stan
 */
public class Userac extends javax.swing.JFrame {

    public Userac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        actionPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        yearDropdown = new javax.swing.JComboBox<>();
        companyDropdown = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 153, 153));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-processor-100.png"))); // NOI18N

        title.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("8 Bits Engineer");

        title1.setFont(new java.awt.Font("Roboto Thin", 0, 12)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("Creating Solutions");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(title1)
                    .addComponent(title)
                    .addComponent(icon))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addGap(48, 48, 48)
                .addComponent(title1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        actionPanel.setBackground(new java.awt.Color(255, 255, 255));

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-cancel-35.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        yearLabel.setBackground(new java.awt.Color(255, 255, 255));
        yearLabel.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(0, 153, 153));
        yearLabel.setText("Select Year");

        yearLabel1.setBackground(new java.awt.Color(255, 255, 255));
        yearLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        yearLabel1.setForeground(new java.awt.Color(0, 153, 153));
        yearLabel1.setText("Select Company");

        yearDropdown.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        yearDropdown.setForeground(new java.awt.Color(0, 153, 153));
        yearDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearDropdownActionPerformed(evt);
            }
        });

        companyDropdown.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        companyDropdown.setForeground(new java.awt.Color(0, 153, 153));

        submitButton.setBackground(new java.awt.Color(0, 153, 153));
        submitButton.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setBorder(null);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(closeLabel))
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(actionPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(companyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearDropdown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(actionPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addComponent(closeLabel)
                .addGap(59, 59, 59)
                .addComponent(yearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(yearLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(actionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 370, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/companyDB?useSSL=false","stan","ladakh1234");
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select value from year");
            while(rs.next()){
                String name = rs.getString("value");
                yearDropdown.addItem(name);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }  

    }//GEN-LAST:event_formWindowActivated


    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        Result res = new Result();
       
           try {
            String company = companyDropdown.getSelectedItem().toString();
            String year = yearDropdown.getSelectedItem().toString();
            String msg = ""; 
            if((company.equals(""))||(year.equals(""))){
                msg = "Sorry no result found";
            }
            else{
                msg = "Result for "+company+" for the year "+year;
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/companyDB?useSSL=false","stan","ladakh1234");
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select * from recruitment where company_id = (select id from company where name = '"+company+"') and year_id = (select id from year where value = '"+year+"')");
            while(rs.next()){
                //String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("individual_name");
                res.jLabel.setText(msg);
                String tbData[] = {name};
                DefaultTableModel tblModel = (DefaultTableModel) res.outputTable.getModel();
                tblModel.addRow(tbData);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
           Userac uac = new Userac();
           uac.setVisible(false);
           dispose();
           res.setVisible(true);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void yearDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearDropdownActionPerformed
try {
            companyDropdown.removeAllItems();
            String year = yearDropdown.getSelectedItem().toString();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/companyDB?useSSL=false","stan","ladakh1234");
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("select name from company where id in (select company_id from recruitment where year_id = (select id from year where value = '"+year+"'))");
            while(rs.next()){
                String name = rs.getString("name");
                companyDropdown.addItem(name);
            }
                       
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_yearDropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       
*/

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JComboBox<String> companyDropdown;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JComboBox<String> yearDropdown;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JLabel yearLabel1;
    // End of variables declaration//GEN-END:variables
}
